[2024-12-29T02:30:32.757+0000] {processor.py:161} INFO - Started process (PID=2800) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-29T02:30:32.759+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-29T02:30:32.761+0000] {logging_mixin.py:188} INFO - [2024-12-29T02:30:32.761+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-29T02:30:32.786+0000] {logging_mixin.py:188} INFO - [2024-12-29T02:30:32.781+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2024-12-29T02:30:32.788+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-29T02:30:32.816+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.065 seconds
