[2025-01-06T12:31:35.239+0000] {processor.py:161} INFO - Started process (PID=2842) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:31:35.251+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:31:35.268+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:31:35.267+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:31:35.323+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:31:35.311+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:31:35.327+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:31:35.385+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.175 seconds
[2025-01-06T12:32:05.598+0000] {processor.py:161} INFO - Started process (PID=2902) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:32:05.599+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:32:05.600+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:32:05.600+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:32:05.624+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:32:05.618+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:32:05.626+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:32:05.653+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.061 seconds
[2025-01-06T12:32:36.036+0000] {processor.py:161} INFO - Started process (PID=2966) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:32:36.037+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:32:36.038+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:32:36.038+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:32:36.062+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:32:36.055+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:32:36.064+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:32:36.097+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.065 seconds
[2025-01-06T12:33:06.601+0000] {processor.py:161} INFO - Started process (PID=3030) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:33:06.603+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:33:06.606+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:33:06.605+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:33:06.639+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:33:06.632+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:33:06.642+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:33:06.686+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.097 seconds
[2025-01-06T12:33:37.113+0000] {processor.py:161} INFO - Started process (PID=3094) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:33:37.114+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:33:37.116+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:33:37.115+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:33:37.155+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:33:37.149+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:33:37.158+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:33:37.223+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.116 seconds
[2025-01-06T12:34:08.008+0000] {processor.py:161} INFO - Started process (PID=3165) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:34:08.010+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:34:08.011+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:34:08.011+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:34:08.036+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:34:08.030+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:34:08.039+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:34:08.067+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.063 seconds
[2025-01-06T12:34:38.392+0000] {processor.py:161} INFO - Started process (PID=3229) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:34:38.395+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:34:38.398+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:34:38.397+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:34:38.439+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:34:38.430+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:34:38.442+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:34:38.482+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.101 seconds
[2025-01-06T12:35:09.005+0000] {processor.py:161} INFO - Started process (PID=3293) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:35:09.006+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:35:09.007+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:35:09.007+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:35:09.033+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:35:09.027+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:35:09.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:35:09.064+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.064 seconds
[2025-01-06T12:35:39.262+0000] {processor.py:161} INFO - Started process (PID=3357) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:35:39.263+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:35:39.265+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:35:39.264+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:35:39.290+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:35:39.284+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:35:39.292+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:35:39.328+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.071 seconds
[2025-01-06T12:36:09.793+0000] {processor.py:161} INFO - Started process (PID=3421) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:36:09.794+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:36:09.795+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:36:09.795+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:36:09.817+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:36:09.811+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:36:09.819+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:36:09.846+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.059 seconds
[2025-01-06T12:36:40.279+0000] {processor.py:161} INFO - Started process (PID=3485) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:36:40.281+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:36:40.282+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:36:40.281+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:36:40.310+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:36:40.303+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:36:40.312+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:36:40.343+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.069 seconds
[2025-01-06T12:37:10.946+0000] {processor.py:161} INFO - Started process (PID=3549) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:37:10.948+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:37:10.949+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:37:10.949+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:37:10.975+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:37:10.968+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:37:10.977+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:37:11.006+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.064 seconds
[2025-01-06T12:37:41.345+0000] {processor.py:161} INFO - Started process (PID=3614) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:37:41.346+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:37:41.348+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:37:41.347+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:37:41.372+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:37:41.366+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:37:41.374+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:37:41.403+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.063 seconds
[2025-01-06T12:38:12.334+0000] {processor.py:161} INFO - Started process (PID=3685) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:38:12.336+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:38:12.338+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:38:12.337+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:38:12.363+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:38:12.355+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:38:12.365+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:38:12.402+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.074 seconds
[2025-01-06T12:38:43.135+0000] {processor.py:161} INFO - Started process (PID=3749) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:38:43.137+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:38:43.138+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:38:43.137+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:38:43.165+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:38:43.157+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:38:43.167+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:38:43.190+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.060 seconds
[2025-01-06T12:39:13.359+0000] {processor.py:161} INFO - Started process (PID=3813) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:39:13.360+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:39:13.362+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:39:13.361+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:39:13.385+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:39:13.378+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:39:13.387+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:39:13.417+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.063 seconds
[2025-01-06T12:39:43.475+0000] {processor.py:161} INFO - Started process (PID=3876) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:39:43.477+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:39:43.478+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:39:43.478+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:39:43.505+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:39:43.499+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:39:43.506+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:39:43.536+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.065 seconds
[2025-01-06T12:40:13.864+0000] {processor.py:161} INFO - Started process (PID=3947) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:40:13.866+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:40:13.868+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:40:13.867+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:40:13.894+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:40:13.887+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:40:13.896+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:40:13.937+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.078 seconds
[2025-01-06T12:40:44.167+0000] {processor.py:161} INFO - Started process (PID=4011) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:40:44.169+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:40:44.170+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:40:44.170+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:40:44.189+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:40:44.183+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:40:44.191+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:40:44.223+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.059 seconds
[2025-01-06T12:41:14.472+0000] {processor.py:161} INFO - Started process (PID=4075) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:41:14.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:41:14.475+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:41:14.474+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:41:14.499+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:41:14.493+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:41:14.502+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:41:14.537+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.070 seconds
[2025-01-06T12:41:44.822+0000] {processor.py:161} INFO - Started process (PID=4146) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:41:44.823+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:41:44.824+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:41:44.824+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:41:44.847+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:41:44.841+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:41:44.849+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:41:44.882+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.064 seconds
[2025-01-06T12:42:15.127+0000] {processor.py:161} INFO - Started process (PID=4210) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:42:15.128+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:42:15.130+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:42:15.129+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:42:15.156+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:42:15.149+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:42:15.158+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:42:15.184+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.061 seconds
[2025-01-06T12:42:45.625+0000] {processor.py:161} INFO - Started process (PID=4274) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:42:45.626+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:42:45.627+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:42:45.627+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:42:45.653+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:42:45.647+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:42:45.655+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:42:45.686+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.066 seconds
[2025-01-06T12:43:15.789+0000] {processor.py:161} INFO - Started process (PID=4345) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:43:15.791+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:43:15.792+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:43:15.792+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:43:15.816+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:43:15.810+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:43:15.818+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:43:15.844+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.060 seconds
[2025-01-06T12:43:46.202+0000] {processor.py:161} INFO - Started process (PID=4409) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:43:46.203+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:43:46.205+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:43:46.205+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:43:46.232+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:43:46.224+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:43:46.235+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:43:46.276+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.078 seconds
[2025-01-06T12:44:16.564+0000] {processor.py:161} INFO - Started process (PID=4473) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:44:16.566+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:44:16.567+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:44:16.566+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:44:16.590+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:44:16.584+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:44:16.592+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:44:16.614+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.055 seconds
[2025-01-06T12:44:46.793+0000] {processor.py:161} INFO - Started process (PID=4544) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:44:46.794+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:44:46.796+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:44:46.796+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:44:46.819+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:44:46.814+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:44:46.822+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:44:46.846+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.060 seconds
[2025-01-06T12:45:17.096+0000] {processor.py:161} INFO - Started process (PID=4608) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:45:17.098+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:45:17.100+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:45:17.099+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:45:17.130+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:45:17.124+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:45:17.132+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:45:17.172+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.081 seconds
[2025-01-06T12:45:47.533+0000] {processor.py:161} INFO - Started process (PID=4672) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:45:47.535+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:45:47.536+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:45:47.536+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:45:47.562+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:45:47.555+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:45:47.564+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:45:47.586+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.058 seconds
[2025-01-06T12:46:17.763+0000] {processor.py:161} INFO - Started process (PID=4743) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:46:17.765+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:46:17.766+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:46:17.765+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:46:17.788+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:46:17.782+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:46:17.790+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:46:17.817+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.057 seconds
[2025-01-06T12:46:48.293+0000] {processor.py:161} INFO - Started process (PID=4807) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:46:48.295+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:46:48.296+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:46:48.296+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:46:48.323+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:46:48.314+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:46:48.325+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:46:48.351+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.062 seconds
[2025-01-06T12:47:19.287+0000] {processor.py:161} INFO - Started process (PID=4872) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:47:19.289+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:47:19.290+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:47:19.290+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:47:19.314+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:47:19.308+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:47:19.316+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:47:19.344+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.061 seconds
[2025-01-06T12:47:49.707+0000] {processor.py:161} INFO - Started process (PID=4943) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:47:49.709+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:47:49.710+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:47:49.710+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:47:49.740+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:47:49.733+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:47:49.742+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:47:49.776+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.073 seconds
[2025-01-06T12:48:20.718+0000] {processor.py:161} INFO - Started process (PID=5007) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:48:20.719+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:48:20.721+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:48:20.720+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:48:20.747+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:48:20.740+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:48:20.749+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:48:20.780+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.066 seconds
[2025-01-06T12:48:51.159+0000] {processor.py:161} INFO - Started process (PID=5071) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:48:51.160+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:48:51.162+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:48:51.161+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:48:51.184+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:48:51.179+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:48:51.186+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:48:51.215+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.061 seconds
[2025-01-06T12:49:21.617+0000] {processor.py:161} INFO - Started process (PID=5142) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:49:21.619+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:49:21.620+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:49:21.620+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:49:21.649+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:49:21.642+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:49:21.651+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:49:21.686+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.074 seconds
[2025-01-06T12:49:51.916+0000] {processor.py:161} INFO - Started process (PID=5206) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:49:51.918+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:49:51.919+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:49:51.919+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:49:51.946+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:49:51.940+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:49:51.948+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:49:51.976+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.066 seconds
[2025-01-06T12:50:22.415+0000] {processor.py:161} INFO - Started process (PID=5270) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:50:22.416+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:50:22.418+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:50:22.417+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:50:22.458+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:50:22.450+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:50:22.460+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:50:22.486+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.075 seconds
[2025-01-06T12:50:52.897+0000] {processor.py:161} INFO - Started process (PID=5341) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:50:52.898+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:50:52.899+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:50:52.899+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:50:52.924+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:50:52.918+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:50:52.926+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:50:52.956+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.064 seconds
[2025-01-06T12:51:23.171+0000] {processor.py:161} INFO - Started process (PID=5405) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:51:23.172+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:51:23.173+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:51:23.173+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:51:23.196+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:51:23.191+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:51:23.198+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:51:23.221+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.055 seconds
[2025-01-06T12:51:53.573+0000] {processor.py:161} INFO - Started process (PID=5469) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:51:53.574+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:51:53.575+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:51:53.575+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:51:53.595+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:51:53.588+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:51:53.598+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:51:53.631+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.061 seconds
[2025-01-06T12:52:24.460+0000] {processor.py:161} INFO - Started process (PID=5539) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:52:24.461+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:52:24.462+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:52:24.462+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:52:24.485+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:52:24.478+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:52:24.487+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:52:24.527+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.074 seconds
[2025-01-06T12:52:54.759+0000] {processor.py:161} INFO - Started process (PID=5603) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:52:54.761+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:52:54.762+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:52:54.761+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:52:54.779+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:52:54.774+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:52:54.780+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:52:54.811+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.057 seconds
[2025-01-06T12:53:25.090+0000] {processor.py:161} INFO - Started process (PID=5667) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:53:25.092+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:53:25.094+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:53:25.093+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:53:25.132+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:53:25.122+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:53:25.135+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:53:25.184+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.101 seconds
[2025-01-06T12:53:55.453+0000] {processor.py:161} INFO - Started process (PID=5738) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:53:55.455+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:53:55.457+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:53:55.457+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:53:55.495+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:53:55.485+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:53:55.498+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:53:55.545+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.099 seconds
[2025-01-06T12:54:25.904+0000] {processor.py:161} INFO - Started process (PID=5803) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:54:25.906+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:54:25.907+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:54:25.906+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:54:25.931+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:54:25.925+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:54:25.933+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:54:25.966+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.065 seconds
[2025-01-06T12:54:56.205+0000] {processor.py:161} INFO - Started process (PID=5867) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:54:56.206+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:54:56.209+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:54:56.208+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:54:56.249+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:54:56.240+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:54:56.252+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:54:56.290+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.093 seconds
[2025-01-06T12:59:11.210+0000] {processor.py:161} INFO - Started process (PID=5932) to work on /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:59:11.211+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2025-01-06T12:59:11.212+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:59:11.211+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:59:11.255+0000] {logging_mixin.py:188} INFO - [2025-01-06T12:59:11.250+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2025-01-06T12:59:11.256+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2025-01-06T12:59:11.276+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.071 seconds
