[2024-12-28T02:50:58.273+0000] {processor.py:161} INFO - Started process (PID=2650) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-28T02:50:58.283+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-28T02:50:58.287+0000] {logging_mixin.py:188} INFO - [2024-12-28T02:50:58.284+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-28T02:50:58.319+0000] {logging_mixin.py:188} INFO - [2024-12-28T02:50:58.313+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2024-12-28T02:50:58.324+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-28T02:50:58.364+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.096 seconds
[2024-12-28T23:29:34.093+0000] {processor.py:161} INFO - Started process (PID=2691) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-28T23:29:34.096+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-28T23:29:34.106+0000] {logging_mixin.py:188} INFO - [2024-12-28T23:29:34.105+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-28T23:29:34.140+0000] {logging_mixin.py:188} INFO - [2024-12-28T23:29:34.127+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2024-12-28T23:29:34.144+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-28T23:29:34.211+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.124 seconds
[2024-12-28T23:30:04.295+0000] {processor.py:161} INFO - Started process (PID=2752) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-28T23:30:04.297+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-28T23:30:04.299+0000] {logging_mixin.py:188} INFO - [2024-12-28T23:30:04.298+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-28T23:30:04.324+0000] {logging_mixin.py:188} INFO - [2024-12-28T23:30:04.317+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 11, in <module>
    from airflow.utils.decorators import task
ImportError: cannot import name 'task' from 'airflow.utils.decorators' (/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/decorators.py)
[2024-12-28T23:30:04.327+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-28T23:30:04.355+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.066 seconds
